apps/api/urls.py
from django.urls import URLPattern, get_resolver, path
from rest_framework import routers
from rest_framework.decorators import api_view
from rest_framework.response import Response

from apps.api.views.view_1.get_all_raw_query import get_all_raw_query
# from ...core.urls import urlpatterns as urlsx

# router = routers.SimpleRouter()
# router = routers.DefaultRouter()
# router.register(prefix="hunter", viewset=get_all_raw_query, basename="hunterx")


def show_urls(urllist, depth=0):
    for entry in urllist:
        print(entry.pattern)
        if hasattr(entry, 'url_patterns'):
            show_urls(entry.url_patterns, depth + 1)


@api_view(["GET"])
def home(request):
    # print(get_resolver().url_patterns)
    # print(URLPattern())
    # print(show_urls(get_resolver().url_patterns))
    return Response({"url": []})


app_name = "api"


urlpatterns = [
    path(
        route="",
        view=home,
        name="home",
    ),
    path(
        route="get-all-raw-queryX",
        view=get_all_raw_query,
        name="get_all_raw_query",
    ),
    # router.urls
]

apps/web/urls.py
from django.urls import path

from apps.web.views.auth.login import login
from apps.web.views.auth.logout import logout
from apps.web.views.auth.register import register
from apps.web.views.home import home
from apps.web.views.view_1.delete_many_by_id import delete_many_by_id
from apps.web.views.view_1.delete_many_by_id_raw_query import \
    delete_many_by_id_raw_query
from apps.web.views.view_1.delete_one_by_id import delete_one_by_id
from apps.web.views.view_1.delete_one_by_id_raw_query import \
    delete_one_by_id_raw_query
from apps.web.views.view_1.get_all import get_all
from apps.web.views.view_1.get_all_raw_query import get_all_raw_query
from apps.web.views.view_1.get_by_id import get_by_id
from apps.web.views.view_1.get_by_id_raw_query import get_by_id_raw_query
from apps.web.views.view_1.insert_many import insert_many
from apps.web.views.view_1.insert_many_raw_query import insert_many_raw_query
from apps.web.views.view_1.insert_one import insert_one
from apps.web.views.view_1.insert_one_raw_query import insert_one_raw_query
from apps.web.views.view_1.update_many_by_id import update_many_by_id
from apps.web.views.view_1.update_many_by_id_raw_query import \
    update_many_by_id_raw_query
from apps.web.views.view_1.update_one_by_id import update_one_by_id
from apps.web.views.view_1.update_one_by_id_raw_query import \
    update_one_by_id_raw_query

app_name = "web"

urlpatterns = [
    path(route="", view=home, name="home"),
    # path(route="", view=get_all, name="home"),

    # Auth
    path(
        route="register/",
        view=register,
        name="register",
    ),
    path(
        route="login/",
        view=login,
        name="login"
    ),
    path(
        route="logout/",
        view=logout,
        name="logout"
    ),

    # 1 - delete
    # path(route="page-1/<int:id>", view=delete_many_by_id, name="delete_many_by_id"),
    # path(route="page-1/<int:id>", view=delete_many_by_id_raw_query,
    #      name="delete_many_by_id_raw_query"),
    path(
        route="page-1/delete-one-by-id/<int:id>",
        view=delete_one_by_id,
        name="delete_one_by_id"
    ),
    # path(route="page-1/<int:id>", view=delete_one_by_id_raw_query,
    #      name="delete_one_by_id_raw_query"),

    # 1 - get
    path(
        route="page-1/",
        view=get_all,
        name="get_all"
    ),
    path(
        route="page-1-raw-query/",
        view=get_all_raw_query,
        name="get_all_raw_query"
    ),
    path(
        route="page-1/<int:id>",
        view=get_by_id,
        name="get_by_id"
    ),
    # path(route="page-1/<int:id>", view=get_by_id_raw_query,
    #      name="get_by_id_raw_query"),

    # 1 - insert
    # path(route="page-1/insert-many", view=insert_many, name="insert_many"),
    # path(route="page-1/insert-many-raw-query", view=insert_many_raw_query,
    #      name="insert_many_raw_query"),
    path(
        route="page-1/insert-one",
        view=insert_one,
        name="insert_one"
    ),
    # path(route="page-1/insert-one-raw-query", view=insert_one_raw_query,
    #      name="insert_one_raw_query"),

    # 1 - update
    # path(route="page-1/<int:id>", view=update_many_by_id, name="update_many_by_id"),
    # path(route="page-1/<int:id>", view=update_many_by_id_raw_query,
    #      name="update_many_by_id_raw_query"),
    path(route="page-1/update-one-by-id/<int:id>",
         view=update_one_by_id, name="update_one_by_id"),
    # path(route="page-1/<int:id>", view=update_one_by_id_raw_query,
    #      name="update_one_by_id_raw_query"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
# from apps.api.urls import router


urlpatterns = [
    path('admin/', admin.site.urls),
    path(route="", view=include(arg="apps.web.urls")),
    path(route="api/", view=include(arg="apps.api.urls")),
    # path(route="api/", view=include(arg=router.urls)),
]

apps/web/models/model_1.py
import uuid
from django.db import models


class Table1(models.Model):
    GENDER = (
        ("Pria", "Pria"),
        ("Wanita", "Wanita"),
    )

    id_field = models.AutoField(primary_key=True, editable=False)
    char_field = models.CharField(max_length=45)
    number_field = models.BigIntegerField(null=True, blank=True)
    email_field = models.EmailField(max_length=225, unique=True)
    choice_field = models.CharField(
        max_length=9, choices=GENDER, null=False, blank=False)
    text_field = models.TextField()
    image_field = models.ImageField(
        upload_to="images/", null=True, blank=True)
    date_time_field = models.DateTimeField(null=True, blank=True)
    # time_field = models.TimeField(null=True, blank=True)
    # file_field = models.FileField(null=True, blank=True)
    date_field = models.DateField(null=True, blank=True)

    class Meta:
        db_table = "table_1"

apps/web/forms/form_1.py
from django import forms

from ..models.model_1 import Table1


class Form1(forms.ModelForm):
    class Meta:
        model = Table1
        fields = "__all__"
        widgets = {
            "char_field": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "autofocus": "autofocus"
                }
            ),
            "number_field": forms.NumberInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "email_field": forms.EmailInput(
                attrs={
                    "class": "form-control"
                }
            ),
            "choice_field": forms.Select(
                attrs={
                    "class": "form-control"
                }
            ),
            "image_field": forms.FileInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "text_field": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 5
                }
            ),
            "date_time_field": forms.DateTimeInput(
                attrs={
                    "class": "form-control",
                    "type": "datetime-local"
                }
            ),
            "date_field": forms.DateInput(
                attrs={
                    "class": "form-control",
                    "type": "date"
                }
            ),
            # "time_field": forms.TimeInput(
            #     attrs={
            #         "class": "form-control",
            #         "type": "time"
            #     }
            # ),
        }

apps/web/views/home.py
# from django.urls import get_resolver, path, URLPattern
from django.shortcuts import render


def home(request):
    # print(get_resolver().reverse_dict.keys())
    return render(request=request, template_name="pages/home.html", context={})

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Template Components</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    {% block css %}{% endblock css %}
  </head>
  <body>
    {% block apps %}{% endblock apps %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    {% block js %}{% endblock js %}
  </body>
</html>

templates/components/icon_delete.html
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="16"
  height="16"
  fill="currentColor"
  class="bi bi-trash-fill"
  viewBox="0 0 16 16"
>
  <path
    d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"
  />
</svg>

templates/components/icon_insert.html
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="16"
  height="16"
  fill="currentColor"
  class="bi bi-plus-square-fill"
  viewBox="0 0 16 16"
>
  <path
    d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"
  />
</svg>

templates/components/icon_reset.html
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="16"
  height="16"
  fill="currentColor"
  class="bi bi-arrow-counterclockwise"
  viewBox="0 0 16 16"
>
  <path
    fill-rule="evenodd"
    d="M8 3a5 5 0 1 1-4.546 2.914.5.5 0 0 0-.908-.417A6 6 0 1 0 8 2z"
  />
  <path
    d="M8 4.466V.534a.25.25 0 0 0-.41-.192L5.23 2.308a.25.25 0 0 0 0 .384l2.36 1.966A.25.25 0 0 0 8 4.466"
  />
</svg>

templates/components/icon_save.html
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="16"
  height="16"
  fill="currentColor"
  class="bi bi-floppy"
  viewBox="0 0 16 16"
>
  <path d="M11 2H9v3h2z" />
  <path
    d="M1.5 0h11.586a1.5 1.5 0 0 1 1.06.44l1.415 1.414A1.5 1.5 0 0 1 16 2.914V14.5a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 14.5v-13A1.5 1.5 0 0 1 1.5 0M1 1.5v13a.5.5 0 0 0 .5.5H2v-4.5A1.5 1.5 0 0 1 3.5 9h9a1.5 1.5 0 0 1 1.5 1.5V15h.5a.5.5 0 0 0 .5-.5V2.914a.5.5 0 0 0-.146-.353l-1.415-1.415A.5.5 0 0 0 13.086 1H13v4.5A1.5 1.5 0 0 1 11.5 7h-7A1.5 1.5 0 0 1 3 5.5V1H1.5a.5.5 0 0 0-.5.5m3 4a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V1H4zM3 15h10v-4.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5z"
  />
</svg>

templates/components/icon_search.html
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="16"
  height="16"
  fill="currentColor"
  class="bi bi-search"
  viewBox="0 0 16 16"
>
  <path
    d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"
  />
</svg>

templates/components/icon_update.html
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="16"
  height="16"
  fill="currentColor"
  class="bi bi-pencil-fill"
  viewBox="0 0 16 16"
>
  <path
    d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"
  />
</svg>

templates/components/navbar.html
<nav class="navbar bg-body-tertiary mb-3">
  <div class="container-fluid">
    <a class="navbar-brand d-sm-none" href="{% url 'web:home' %}">DTC</a>
    <a class="navbar-brand d-none d-sm-block" href="{% url 'web:home' %}"
      >Django Template Components</a
    >
    <span class="ms-auto me-3 d-none d-sm-block"
      >Hello <b>{{user}}</b>. Have a nice day</span
    >
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="offcanvas"
      data-bs-target="#offcanvasNavbar"
      aria-controls="offcanvasNavbar"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      class="offcanvas offcanvas-end"
      tabindex="-1"
      id="offcanvasNavbar"
      aria-labelledby="offcanvasNavbarLabel"
    >
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
          Django Template Components
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="offcanvas"
          aria-label="Close"
        ></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item border rounded px-2 mb-2">
            <a class="nav-link" aria-current="page" href="{% url 'web:home' %}"
              >Home</a
            >
          </li>
          <li class="nav-item border rounded px-2">
            <a class="nav-link" aria-current="page" href="#">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

templates/pages/home.html
<!--  -->{% extends "base.html" %}<!--  -->

<!--  -->{% block apps %}<!--  -->
<!--  -->{% include "components/navbar.html"%}<!--  -->
<div class="container-fluid">
  <div class="row row-cols-auto">
    <div class="col mb-3">
      <div class="card border me-1" style="min-width: 20rem">
        <div class="card-header text-center h3">REST API</div>
        <div class="card-body text-light">
          <a
            href="{% url 'api:home' %}"
            class="btn btn-secondary card-title d-grid"
            >Open</a
          >
        </div>
      </div>
    </div>

    <div class="col mb-3">
      <div class="card border me-1" style="min-width: 20rem">
        <div class="card-header text-center h3">WEB APP</div>
        <div class="card-body text-light">
          <a
            href="{% url 'web:get_all' %}"
            class="btn btn-secondary card-title d-grid"
            >Open</a
          >
        </div>
      </div>
    </div>

    <div class="col mb-3">
      <div class="card border me-1" style="min-width: 20rem">
        <div class="card-header text-center h3">WEB APP RAW QUERY</div>
        <div class="card-body text-light">
          <a
            href="{% url 'web:get_all_raw_query' %}"
            class="btn btn-secondary card-title d-grid"
            >Open</a
          >
        </div>
      </div>
    </div>

    <div class="col mb-3">
      <div class="card border me-1" style="min-width: 20rem">
        <div class="card-header text-center h3">New</div>
        <div class="card-body text-light">
          <a
            href="{% url 'web:get_all_raw_query' %}"
            class="btn btn-secondary card-title d-grid"
            >Open</a
          >
        </div>
      </div>
    </div>

    <div class="col mb-3">
      <div class="card border me-1" style="min-width: 20rem">
        <div class="card-header text-center h3">New-baru</div>
        <div class="card-body text-light">
          <a
            href="{% url 'web:get_all_raw_query' %}"
            class="btn btn-secondary card-title d-grid"
            >Open</a
          >
        </div>
      </div>
    </div>
  </div>
</div>
<!--  -->{% endblock apps %}<!--  -->

templates/pages/page_1/get_all_list.html
<!- -  - ->{%extends "base.html"%}<!- -  - ->

<!- -  - ->{%block apps%}<!- -  - ->
<!- -  - ->{% include "components/navbar.html"%}<!- -  - ->
<div class="container-fluid">
  <div class="row row-cols-auto mb-3">
    <div class="col mb-3">
      <a
        href="{% url 'web:insert_one' %}"
        class="btn btn-secondary btn-sm"
        title="Insert One"
      >
        <!- -  - ->{% include "components/icon_insert.html" %}<!- -  - ->
        One
      </a>
      <a href="#" class="btn btn-secondary btn-sm" title="Insert Many">
        <!- -  - ->{% include "components/icon_insert.html" %}<!- -  - ->
        Many
      </a>
      <a href="#" class="btn btn-secondary btn-sm" title="Delete Many">
        <!- -  - ->{% include "components/icon_delete.html" %}<!- -  - ->
        Many
      </a>
      <a href="#" class="btn btn-secondary btn-sm" title="Update Many">
        <!- -  - ->{% include "components/icon_update.html" %}<!- -  - ->
        Many
      </a>
    </div>

    <!-- pagination -->
    <div class="col ms-auto">
      <!- -  - ->{% if data.has_other_pages %}<!- -  - ->
      <ul class="pagination pagination-sm">
        <!- -  - ->{% if data.has_previous %}<!- -  - ->
        <li class="page-item">
          <a class="page-link" href="?page={{ data.previous_page_number }}"
            >Previous</a
          >
        </li>
        <!- -  - ->{% else %}<!- -  - ->
        <li class="disabled page-item">
          <a class="page-link" href="#">Previous</a>
        </li>
        <!- -  - ->{% endif %}<!- -  - ->

        <!- -  - ->{% for i in data.paginator.page_range %}<!- -  - ->
        <!- -  - ->{% if data.number == i %}<!- -  - ->
        <li class="active page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        <!- -  - ->{% else %}<!- -  - ->
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        <!- -  - ->{% endif %}<!- -  - ->
        <!- -  - ->{% endfor %}<!- -  - ->

        <!- -  - ->{% if data.has_next %}<!- -  - ->
        <li class="page-item">
          <a class="page-link" href="?page={{ data.next_page_number }}">Next</a>
        </li>
        <!- -  - ->{% else %}<!- -  - ->
        <li class="disabled page-item">
          <a class="page-link" href="#">Next</a>
        </li>
        <!- -  - ->{% endif %}<!- -  - ->
      </ul>
      <!- -  - ->{% endif %}<!- -  - ->
    </div>

    <!-- search -->
    <div class="col ms-auto">
      <form class="d-flex">
        <select id="disabledSelect" class="form-select">
          <option>Char Field</option>
          <option>Number Field</option>
          <option>Email Field</option>
          <option>Choice Field</option>
          <option>Text Field</option>
        </select>
        <input
          type="text"
          class="form-control"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
        />
        <button type="submit" class="btn btn-secondary btn-sm">
          <!- -  - ->{% include "components/icon_search.html" %}<!- -  - ->
        </button>
      </form>
    </div>
  </div>

  <!-- data table -->
  <div class="table-responsive-xxl">
    <table class="table table-hover">
      <thead class="table-light">
        <tr>
          <!-- <th scope="col" class="text-center">#</th> -->
          <th scope="col" style="min-width: 250px">Char Field</th>
          <th scope="col" style="min-width: 250px">Number Field</th>
          <th scope="col" style="min-width: 250px">Email Field</th>
          <th scope="col" style="min-width: 250px">Choice Field</th>
          <th scope="col" style="min-width: 150px">Text Field</th>
          <th scope="col" class="text-center" colspan="3">Action</th>
        </tr>
      </thead>
      <tbody>
        <!- -  - ->{% for i in data %}<!- -  - ->
        <tr>
          <!-- <th scope="row" class="text-center">{{forloop.counter}}</th> -->
          <td>{{i.char_field}}</td>
          <td>{{i.number_field}}</td>
          <td>{{i.email_field}}</td>
          <td>{{i.choice_field}}</td>
          <td>{{i.text_field}}</td>
          <td class="text-center" style="width: 0px">
            <a href="#" class="btn btn-sm btn-secondary" title="Update">
              <!- -  - ->{% include "components/icon_update.html" %}<!- -  - ->
            </a>
          </td>
          <td class="text-center" style="width: 0px">
            <button
              type="button"
              class="btn btn-sm btn-secondary"
              data-bs-toggle="modal"
              data-bs-target="#modalDeleteData"
              title="Delete"
            >
              <!- -  - ->{% include "components/icon_delete.html" %}<!- -  - ->
            </button>
            <!-- Modal Delete -->
            <div
              class="modal fade"
              id="modalDeleteData"
              tabindex="-1"
              aria-labelledby="exampleModalLabel"
              aria-hidden="true"
            >
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header bg-secondary">
                    <h1
                      class="modal-title fs-5 text-white"
                      id="exampleModalLabel"
                    >
                      Peringatan
                    </h1>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                    ></button>
                  </div>
                  <div class="modal-body">
                    Apakah Kamu yakin akan menghapus data tersebut...?
                  </div>
                  <div class="modal-footer">
                    <a href="#" class="btn btn-secondary">Iya</a>
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-bs-dismiss="modal"
                    >
                      Tidak
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </td>
          <td class="text-center" style="width: 0px">
            <a href="#" class="btn btn-sm btn-secondary" title="View">
              <!- -  - ->{% include "components/icon_view.html" %}<!- -  - ->
            </a>
          </td>
        </tr>
        <!- -  - ->{% endfor %}<!- -  - ->
      </tbody>
    </table>
  </div>
</div>

<!- -  - ->{%endblock apps%}<!- -  - ->

templates/pages/page_1/get_by_id.html
<!- -  - ->{%extends "base.html"%}<!- -  - ->

<!- -  - ->{%block apps%}<!- -  - ->
<!- -  - ->{%include "components/navbar.html"%}<!- -  - ->
<div class="container-fluid">
  <div class="card border">
    <div class="card-header text-bg-light">
      <div class="h3 text-center">Get By ID</div>
    </div>
    <div class="card-body">
      <fieldset disabled>
        <div class="row mb-3">
          <div class="col">
            <div class="mb-2">
              <!- -  - ->{{data.form.char_field.label}}<!- -  - ->
            </div>
            <input class="form-control" value="{{data.model.char_field}}" />
          </div>
          <div class="col">
            <div class="mb-2">
              <!- -  - ->{{data.form.email_field.label}}<!- -  - ->
            </div>
            <input class="form-control" value="{{data.model.email_field}}" />
          </div>
        </div>
        <div class="row mb-3">
          <div class="col">
            <div class="mb-2">
              <!- -  - ->{{data.form.number_field.label}}<!- -  - ->
            </div>
            <input class="form-control" value="{{data.model.number_field}}" />
          </div>
          <div class="col">
            <div class="mb-2">
              <!- -  - ->{{data.form.choice_field.label}}<!- -  - ->
            </div>
            <input class="form-control" value="{{data.model.choice_field}}" />
          </div>
        </div>
        <div class="row mb-3">
          <div class="col">
            <div class="mb-2">
              <!- -  - ->{{data.form.image_field.label}}<!- -  - ->
            </div>
            <img src="{{data.model.image.url}}" alt="" width="150px" />
          </div>
          <div class="col">
            <div class="mb-2">
              <!- -  - ->{{data.form.text_field.label}}<!- -  - ->
            </div>
            <textarea class="form-control" rows="5">
{{data.model.text_field}}
            </textarea>
          </div>
          <div class="col">
            <div class="mb-2">
              <!- -  - ->{{data.form.date_time_field.label}}<!- -  - ->
            </div>
            <input
              class="form-control"
              type="datetime-local"
              disabled
              value="{{data.model.date_time_field|date:'Y-m-d'}}T{{data.model.date_time_field|time:'h:i'}}"
            />
          </div>
          <div class="col">
            <div class="mb-2">
              <!- -  - ->{{data.form.date_field.label}}<!- -  - ->
            </div>
            <input
              class="form-control"
              type="date"
              disabled
              value="{{data.model.date_time_field|date:'Y-m-d'}}"
            />
          </div>
        </div>
      </fieldset>
      <a
        href="{% url 'web:update_one_by_id' data.model.id_field %}"
        class="btn btn-outline-secondary me-3"
        title="Update"
      >
        <!- -  - ->{% include "components/icon_update.html" %}<!- -  - ->
        Update
      </a>
      <button
        type="button"
        class="btn btn-outline-secondary"
        data-bs-toggle="modal"
        data-bs-target="#modalDeleteData"
        title="Delete"
      >
        <!- -  - ->{% include "components/icon_delete.html" %}<!- -  - ->
        Delete
      </button>
    </div>
  </div>
</div>

<!-- Modal Delete -->
<div
  class="modal fade"
  id="modalDeleteData"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-secondary">
        <h1 class="modal-title fs-5 text-white" id="exampleModalLabel">
          Peringatan
        </h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        Apakah Kamu yakin akan menghapus data tersebut...?
      </div>
      <div class="modal-footer">
        <a
          href="{% url 'web:delete_one_by_id' data.model.id_field %}"
          class="btn btn-secondary"
          >Iya</a
        >
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Tidak
        </button>
      </div>
    </div>
  </div>
</div>

<!- -  - ->{%endblock apps%}<!- -  - ->